"""
src/athena/domain/entities/notification.py
============================================
Notification domain entity.

Design rules:
    - Zero external / framework imports.
    - Status transitions are explicit named methods.
"""
from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional


class NotificationPriority(str, Enum):
    """Urgency level of a Notification.

    The NotificationPolicyEngine uses priority together with UserState to
    decide whether to deliver immediately, queue, or drop.
    """

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    URGENT = "urgent"


class NotificationStatus(str, Enum):
    """Delivery / interaction lifecycle of a Notification."""

    UNREAD = "unread"
    """Delivered to the UI but not yet acknowledged by the user."""

    READ = "read"
    """User opened or acknowledged the notification."""

    DISMISSED = "dismissed"
    """User explicitly closed / dismissed the notification."""

    QUEUED = "queued"
    """Held back by the policy engine; not yet delivered to the UI."""


@dataclass
class Notification:
    """Core notification domain entity.

    Represents a single alert generated by an agent or system component
    that may be delivered to the user via the desktop UI.

    Attributes
    ----------
    agent_id:
        Identifier of the agent or system component that created this
        notification (e.g. ``'task_agent'``, ``'memory_consolidator'``).
    title:
        Short headline shown in the notification popup.
    body:
        Full message body. May contain Markdown for rich rendering.
    id:
        Globally unique UUID string, auto-generated on creation.
    priority:
        Urgency level used by the policy engine for routing decisions.
    status:
        Current delivery / interaction state.
    action_label:
        Optional CTA button label (e.g. ``'Open Task'``).
    action_payload:
        Arbitrary dict passed to the action handler when the CTA is clicked.
    created_at:
        UTC timestamp when the notification was created.
    delivered_at:
        UTC timestamp when it was actually shown to the user. ``None`` if
        still queued.
    """

    agent_id: str
    title: str
    body: str
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    priority: NotificationPriority = NotificationPriority.MEDIUM
    status: NotificationStatus = NotificationStatus.QUEUED
    action_label: str = ""
    action_payload: dict = field(default_factory=dict)
    created_at: datetime = field(default_factory=datetime.utcnow)
    delivered_at: Optional[datetime] = None

    # ------------------------------------------------------------------ #
    #  Domain behaviour                                                    #
    # ------------------------------------------------------------------ #

    def dismiss(self) -> None:
        """Transition status to DISMISSED.

        Raises
        ------
        ValueError
            If the notification is already DISMISSED.
        """
        raise NotImplementedError("dismiss logic not yet implemented")

    def mark_read(self) -> None:
        """Transition status to READ.

        Raises
        ------
        ValueError
            If the notification is already READ or DISMISSED.
        """
        raise NotImplementedError("mark_read logic not yet implemented")

    def deliver(self) -> None:
        """Transition status from QUEUED → UNREAD and set delivered_at to now.

        Raises
        ------
        ValueError
            If the notification is not in QUEUED status.
        """
        raise NotImplementedError("deliver logic not yet implemented")

    def is_actionable(self) -> bool:
        """Return True when the notification has a non-empty action_label.

        Returns
        -------
        bool
            ``True`` if ``action_label`` is a non-empty string.
        """
        raise NotImplementedError("is_actionable logic not yet implemented")
